Repository Mathieu-Lala/game_project, pull requests merged in 2020-12, with the labels that each got.

#158 Feat/game balance
  data/db/classes.json
  data/db/enemies.json
  src/Application/src/GameLogic/fight.cpp
  src/Application/src/factory/EntityFactory.cpp
Labels: priority:normal, scope:character

#159 Doc/readme update
  .github/workflows/main.yaml
  README.md
  data/db/spells.json
  doc/history/README.md
  doc/history/app_v0.1.9.png
  doc/history/app_v0.2.12.gif
Labels: doc

#160 Feat/keyboard binds rework
  data/db/spells.json
  data/img/menu/how_to_play/controls.png
  src/Application/include/component/ControllerAxis.hpp
  src/Application/src/GameLogic.cpp
  src/Application/src/GameLogic/collision.cpp
  src/Application/src/menu/AMenu.cpp
  src/Application/src/menu/UpgradePanel.cpp
Labels: feature, priority:high

#157 [ADD] skeleton anim
  data/animation/enemies/skeleton/skeleton.data.json
  data/animation/enemies/skeleton/spritesheet/attack_left.png
  src/Application/include/models/Stage.hpp
  src/Application/src/factory/SpellFactory.cpp
Labels: feature

#161 Tweaks
  data/db/enemies.json
  data/db/spells.json
Labels: fix, scope:character

#162 Feat/game balancev2
  data/config/app.ini.last
  data/config/imgui.ini
  data/db/classes.json
  data/db/enemies.json
  data/db/spells.json
  src/Application/include/models/Enemy.hpp
  src/Application/src/GameLogic/fight.cpp
  src/Application/src/factory/ParticuleFactory.cpp
  src/Application/src/widgets/GameHUD.cpp
Labels: feature, priority:high
